# -*- coding: utf-8 -*-
"""cv-co1-at1-q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIfS4Z73zwRt2F0z6ZuJTAL_qYpgrePN
"""

# Install required library (already available in Colab)
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
image = cv2.imread('8.jpg')

# Resize for display (optional)
image = cv2.resize(image, (500, 350))

# Generate Gaussian noise
mean = 0
sigma = 25

gaussian = np.random.normal(mean, sigma, image.shape).astype(np.int16)

# Add noise to image
noisy = image.astype(np.int16) + gaussian
noisy = np.clip(noisy, 0, 255).astype(np.uint8)

# Apply Gaussian Blur
gaussian_blur = cv2.GaussianBlur(noisy, (5,5), 0)

# Apply Median Filter
median = cv2.medianBlur(noisy, 5)

# Apply Bilateral Filter
bilateral = cv2.bilateralFilter(noisy, 9, 75, 75)

# Display images
print("Original Image")
cv2_imshow(image)

print("Noisy Image")
cv2_imshow(noisy)

print("Gaussian Blur Result")
cv2_imshow(gaussian_blur)

print("Median Filter Result")
cv2_imshow(median)

print("Bilateral Filter Result")
cv2_imshow(bilateral)

# Save outputs
cv2.imwrite("Noisy_Image.jpg", noisy)
cv2.imwrite("Gaussian_Blur.jpg", gaussian_blur)
cv2.imwrite("Median_Filter.jpg", median)
cv2.imwrite("Bilateral_Filter.jpg", bilateral)