# -*- coding: utf-8 -*-
"""cv-co1-at2-q01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH9LIeDnKIHIKSdTlR1suBTIrTUdUzOW
"""

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

import cv2
from google.colab.patches import cv2_imshow
from graphviz import Digraph

# Read and display the input image
img = cv2.imread("1.jpg")

if img is None:
    print("Error: Upload the image as 'scene.jpg'")
else:
    print("INPUT IMAGE")
    cv2_imshow(img)

# Create Concept Map
dot = Digraph("Digital_Image_Pipeline", format="png")

dot.attr(rankdir="LR")
dot.attr(
    "node",
    shape="box",
    style="filled",
    fillcolor="lightyellow",
    color="black",
    fontname="Arial"
)

# Nodes
dot.node("A","Real-World Scene")
dot.node("B","Light Source")
dot.node("C","Object Reflection")
dot.node("D","Camera Lens")
dot.node("E","Image Sensor\n(CCD / CMOS)")
dot.node("F","Image Acquisition")
dot.node("G","Analog Signal")
dot.node("H","Sampling")
dot.node("I","Quantization")
dot.node("J","Digital Image")
dot.node("K","Pixels")
dot.node("L","Resolution")
dot.node("M","RGB Color Model")
dot.node("N","Noise")
dot.node("O","Image Enhancement")
dot.node("P","Filtering")
dot.node("Q","Histogram Analysis")
dot.node("R","Segmentation")
dot.node("S","Feature Extraction")
dot.node("T","Machine Learning")
dot.node("U","Computer Vision")
dot.node("V","Object Recognition")
dot.node("W","Decision Making")

# Main Pipeline
dot.edge("A","B","Illuminated by")
dot.edge("B","C","Produces")
dot.edge("C","D","Captured by")
dot.edge("D","E","Focuses Light")
dot.edge("E","F","Converts Photons")
dot.edge("F","G","Generates")
dot.edge("G","H","Spatial Sampling")
dot.edge("H","I","Intensity Quantization")
dot.edge("I","J","Creates")
dot.edge("J","K","Contains")
dot.edge("K","O","Processed")
dot.edge("O","P","Noise Reduction")
dot.edge("P","Q","Image Analysis")
dot.edge("Q","R","Object Separation")
dot.edge("R","S","Extract Features")
dot.edge("S","T","Training")
dot.edge("T","U","Prediction")
dot.edge("U","V","Recognition")
dot.edge("V","W","Decision")

# Supporting Relationships
dot.edge("L","J","Determines Quality")
dot.edge("M","J","Represents Colors")
dot.edge("N","E","Sensor Noise")
dot.edge("N","O","Removed By")

# Generate Concept Map
dot.render("Concept_Map", view=False)

# Display Concept Map
concept = cv2.imread("Concept_Map.png")

print("\nCONCEPT MAP")
cv2_imshow(concept)

# Save Output
cv2.imwrite("Digital_Image_Concept_Map.png", concept)

print("\nConcept Map saved successfully as 'Digital_Image_Concept_Map.png'")