# -*- coding: utf-8 -*-
"""cv-co1-at1-q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTqOTqMRk_bCRLPsvkvNhRs_bYeOq50W
"""

import cv2
from google.colab.patches import cv2_imshow

# Read image
image = cv2.imread("10.jpg")

# Resize original image
image = cv2.resize(image, (600,400))

# Simulate low-resolution image
low_res = cv2.resize(image, (100,70))

# Upscale back to original size
upscaled = cv2.resize(low_res, (600,400), interpolation=cv2.INTER_NEAREST)

# Display images
print("Original High Resolution Image")
cv2_imshow(image)

print("Low Resolution (Upscaled for Viewing)")
cv2_imshow(upscaled)

# Save outputs
cv2.imwrite("Original.jpg", image)
cv2.imwrite("LowResolution.jpg", upscaled)