# -*- coding: utf-8 -*-
"""cv-co1-at2-q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kCC6CBB9o6tnorGvLXs2jnosw6La89S
"""

# ============================================================
# CONCEPT MAP: SAMPLING, ALIASING & IMAGE DISTORTION
# Google Colab Code
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

from graphviz import Digraph
from IPython.display import Image, display

# ------------------------------------------------------------
# Create Concept Map
# ------------------------------------------------------------
dot = Digraph("SamplingAliasing", format="png")

# Graph settings
dot.attr(rankdir="TB")
dot.attr(size="16,16")
dot.attr(dpi="300")
dot.attr(nodesep="0.5")
dot.attr(ranksep="0.8")
dot.attr(splines="ortho")

# ============================================================
# MAIN NODE
# ============================================================

dot.node(
    "A",
    "SAMPLING,\nALIASING &\nIMAGE DISTORTION",
    shape="box",
    style="filled",
    fillcolor="lightblue",
    fontsize="22"
)

# ============================================================
# SAMPLING
# ============================================================

dot.node(
    "B",
    "Sampling",
    shape="box",
    style="filled",
    fillcolor="lightgreen"
)

dot.node("C","Sampling Rate",shape="ellipse")
dot.node("D","Nyquist Sampling\nCriterion",shape="ellipse")
dot.node("E","Spatial Resolution",shape="ellipse")

# ============================================================
# ALIASING
# ============================================================

dot.node(
    "F",
    "Aliasing",
    shape="box",
    style="filled",
    fillcolor="lightcoral"
)

dot.node("G","Undersampling",shape="ellipse")
dot.node("H","False Patterns",shape="ellipse")
dot.node("I","Jagged Edges",shape="ellipse")
dot.node("J","Moiré Patterns",shape="ellipse")

# ============================================================
# IMAGE DISTORTION
# ============================================================

dot.node(
    "K",
    "Image Distortion",
    shape="box",
    style="filled",
    fillcolor="salmon"
)

dot.node("L","Loss of Detail",shape="ellipse")
dot.node("M","Blurred Appearance",shape="ellipse")
dot.node("N","Reduced Image Quality",shape="ellipse")

# ============================================================
# SOLUTIONS
# ============================================================

dot.node(
    "O",
    "Prevention Methods",
    shape="box",
    style="filled",
    fillcolor="khaki"
)

dot.node("P","Increase Sampling Rate",shape="ellipse")
dot.node("Q","Anti-Aliasing Filter",shape="ellipse")
dot.node("R","Higher Resolution Sensor",shape="ellipse")

# ============================================================
# APPLICATIONS
# ============================================================

dot.node(
    "S",
    "Applications",
    shape="box",
    style="filled",
    fillcolor="lightskyblue"
)

dot.node("T","Medical Imaging",shape="box")
dot.node("U","Remote Sensing",shape="box")
dot.node("V","Autonomous Vehicles",shape="box")
dot.node("W","Face Recognition",shape="box")
dot.node("X","Industrial Inspection",shape="box")

# ============================================================
# LITERATURE
# ============================================================

dot.node(
    "Y",
    "Theoretical Insights\n\n"
    "• Gonzalez & Woods\nDigital Image Processing\n\n"
    "• Richard Szeliski\nComputer Vision\n\n"
    "• Forsyth & Ponce\nComputer Vision\n\n"
    "• Shannon–Nyquist Sampling Theory",
    shape="note",
    style="filled",
    fillcolor="lightyellow"
)

# ============================================================
# CONNECTIONS
# ============================================================

# Main Branches
dot.edge("A","B")
dot.edge("A","F")
dot.edge("A","K")

# Sampling
dot.edge("B","C")
dot.edge("C","D",label="must satisfy")
dot.edge("D","E",label="ensures")

# Cause of aliasing
dot.edge("C","G",label="low rate causes")
dot.edge("G","F")

# Effects of aliasing
dot.edge("F","H")
dot.edge("F","I")
dot.edge("F","J")

# Image distortion
dot.edge("H","K")
dot.edge("I","K")
dot.edge("J","K")

dot.edge("K","L")
dot.edge("K","M")
dot.edge("K","N")

# Prevention
dot.edge("N","O",label="minimized by")
dot.edge("O","P")
dot.edge("O","Q")
dot.edge("O","R")

# Applications
dot.edge("O","S",label="improves")
dot.edge("S","T")
dot.edge("S","U")
dot.edge("S","V")
dot.edge("S","W")
dot.edge("S","X")

# Literature
dot.edge("Y","A",label="supported by")

# ============================================================
# SAVE & DISPLAY
# ============================================================

filename = dot.render("Sampling_Aliasing_Image_Distortion_Concept_Map")

display(Image(filename))

print("Concept Map generated successfully!")