# -*- coding: utf-8 -*-
"""Lab exp 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIPv0fEvlrPnZZdfwCABxln1nas3ZPFf
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
img = cv2.imread('Sample.jpg',cv2.IMREAD_GRAYSCALE)
kernel = np.ones((5,5), np.uint8)
dilated_img = cv2.dilate(img, kernel, iterations=1)
cv2.imwrite('Dilated_Image.jpg', dilated_img)
cv2_imshow(dilated_img)
cv2_waitKey(0)
cv2_destroyAllWindows()