# -*- coding: utf-8 -*-
"""cv-co1-at1-q07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8WKQrzz3zKTWUYD2mDOv-96AlW-SFYb
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read grayscale image
image = cv2.imread('grayscale.jpg', cv2.IMREAD_GRAYSCALE)

# Check if image is loaded
if image is None:
    print("Error: Image not found!")
else:

    # 8-bit image (256 gray levels)
    original = image.copy()

    # 6-bit quantization (64 gray levels)
    quant_64 = (image // 4) * 4

    # 4-bit quantization (16 gray levels)
    quant_16 = (image // 16) * 16

    # 2-bit quantization (4 gray levels)
    quant_4 = (image // 64) * 64

    # Display results
    plt.figure(figsize=(16,5))

    plt.subplot(1,4,1)
    plt.imshow(original, cmap='gray')
    plt.title("Original (256 Levels)")
    plt.axis('off')

    plt.subplot(1,4,2)
    plt.imshow(quant_64, cmap='gray')
    plt.title("64 Gray Levels")
    plt.axis('off')

    plt.subplot(1,4,3)
    plt.imshow(quant_16, cmap='gray')
    plt.title("16 Gray Levels")
    plt.axis('off')

    plt.subplot(1,4,4)
    plt.imshow(quant_4, cmap='gray')
    plt.title("4 Gray Levels")
    plt.axis('off')

    plt.show()