# -*- coding: utf-8 -*-
"""cv-co1-at2-q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNgmK6naCFyOeABiEaXnKKdZmjV82YQo
"""

# ============================================================
# Concept Map: Computer Vision System Pipeline
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

import cv2
from google.colab.patches import cv2_imshow
from graphviz import Digraph

# ------------------------------------------------------------
# Read and display input image
# ------------------------------------------------------------
img = cv2.imread("input.jpg")

if img is None:
    print("Upload an image named 'input.jpg'")
else:
    print("Sample Input Image")
    cv2_imshow(img)

# ------------------------------------------------------------
# Create Concept Map
# ------------------------------------------------------------
dot = Digraph("Computer_Vision_Concept_Map", format="png")

dot.attr(rankdir="TB", size="14,14")

dot.attr("node",
         shape="box",
         style="rounded,filled",
         fillcolor="lightblue",
         fontname="Arial",
         fontsize="11")

# Main Stages

dot.node("A","Real-World Scene")

dot.node("B","Image Acquisition\n(Camera / Sensor)")

dot.node("C","Image Formation\nLighting + Lens")

dot.node("D","Preprocessing\nNoise Removal\nResizing\nNormalization")

dot.node("E","Feature Extraction\nEdges\nCorners\nTexture\nColor")

dot.node("F","Image Segmentation")

dot.node("G","Object Detection")

dot.node("H","Feature Representation")

dot.node("I","Machine Learning /\nDeep Learning")

dot.node("J","Classification /\nRecognition")

dot.node("K","Decision Making")

dot.node("L","Meaningful Output\nPrediction\nTracking\nAnalysis")

# Supporting Concepts

dot.node("M","Sampling")

dot.node("N","Quantization")

dot.node("O","Pixels")

dot.node("P","RGB Color Model")

dot.node("Q","CNN")

dot.node("R","OpenCV")

dot.node("S","Research Literature\nComputer Vision\nDigital Image Processing")

# Main Pipeline

dot.edge("A","B","Captured")

dot.edge("B","C","Creates")

dot.edge("C","D","Produces")

dot.edge("D","E","Improves")

dot.edge("E","F","Supports")

dot.edge("F","G","Locate Objects")

dot.edge("G","H","Generate Features")

dot.edge("H","I","Input")

dot.edge("I","J","Predict")

dot.edge("J","K","Assist")

dot.edge("K","L","Generate")

# Supporting Relationships

dot.edge("M","B","Image Acquisition")

dot.edge("N","B","Digital Conversion")

dot.edge("O","C","Image Representation")

dot.edge("P","C","Color Information")

dot.edge("Q","I","Deep Learning")

dot.edge("R","D","Implementation")

dot.edge("S","D","Based on")

dot.edge("S","E","Based on")

dot.edge("S","I","Based on")

# Render

dot.render("ComputerVisionConceptMap", view=False)

# ------------------------------------------------------------
# Display Concept Map
# ------------------------------------------------------------

concept = cv2.imread("ComputerVisionConceptMap.png")

print("\nHierarchical Concept Map")

cv2_imshow(concept)

cv2.imwrite("ComputerVision_Concept_Map.png", concept)

print("\nSaved as ComputerVision_Concept_Map.png")