# -*- coding: utf-8 -*-
"""Lab exp 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zk5R-c1fxo6OPK6mfXwwggX6AMmtwy1r
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
img = cv2.imread('Sample.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 100, 200)
cv2.imwrite('Canny_Edges_3rd.jpg', edges)
cv2_imshow(edges)
cv2.waitKey(0)
cv2.destroyAllWindows()