# -*- coding: utf-8 -*-
"""Lab Session 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReLrEM2rZSMWnPm6yXKg8uxEvqkkRNM2
"""

import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread ('Sample.jpg')
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite('gray_image.jpg', gray_img)
grayimg1=cv2.resize(gray_img,(300,200))
cv2_imshow(grayimg1)
cv2.waitKey(0)
cv2.destroyAllWindows()