# -*- coding: utf-8 -*-
"""cv-co1-at1-q09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYua-u-2QZ5GxWeGxy8QIP7ccfazCMuh
"""

import cv2
from google.colab.patches import cv2_imshow

# Load Haar Cascade
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

# Read image
image = cv2.imread('9.jpg')

# Resize image
image = cv2.resize(image, (500, 500))

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect faces
faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30,30)
)

# Draw rectangle around detected faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,0), 2)

print("Detected Faces:", len(faces))

cv2_imshow(image)

cv2.imwrite("Detected_Face.jpg", image)