# -*- coding: utf-8 -*-
"""cv-co1-at1-q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19x6uEI4JY0i3x1DMYOLGSsS2mTq80IBs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
image = cv2.imread('Sample.jpg')

# Convert BGR to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# -------------------------------
# Step 1: Simulate Low Light
# -------------------------------
low_light = (image * 0.25).astype(np.uint8)

# -------------------------------
# Step 2: Add Sensor Noise
# -------------------------------
noise = np.random.normal(0, 20, low_light.shape).astype(np.int16)

noisy = low_light.astype(np.int16) + noise
noisy = np.clip(noisy, 0, 255).astype(np.uint8)

# -------------------------------
# Step 3: Simulate Blur
# -------------------------------
blurred = cv2.GaussianBlur(noisy, (7,7), 2)

# -------------------------------
# Step 4: Brightness Enhancement
# -------------------------------
gray = cv2.cvtColor(blurred, cv2.COLOR_RGB2GRAY)

equalized = cv2.equalizeHist(gray)

# -------------------------------
# Display Results
# -------------------------------
titles = ['Original',
          'Low Light',
          'Sensor Noise',
          'Blurred',
          'Enhanced']

images = [image,
          low_light,
          noisy,
          blurred,
          equalized]

plt.figure(figsize=(18,8))

for i in range(len(images)):
    plt.subplot(1,5,i+1)

    if len(images[i].shape)==2:
        plt.imshow(images[i], cmap='gray')
    else:
        plt.imshow(images[i])

    plt.title(titles[i])
    plt.axis('off')

plt.show()