# -*- coding: utf-8 -*-
"""cv-co1-at2-q05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUSSm2SLQRjzgtwa4zwWF9iFB7EeMQp-
"""

# ============================================================
# CONCEPT MAP: SYSTEM CAPABILITIES AND VISION-BASED APPLICATIONS
# Google Colab Code
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

from graphviz import Digraph
from IPython.display import Image, display

# Create graph
dot = Digraph("SystemCapabilities", format="png")

# Layout settings
dot.attr(rankdir="TB")
dot.attr(size="16,16")
dot.attr(dpi="300")
dot.attr(nodesep="0.5")
dot.attr(ranksep="0.8")

# ============================================================
# MAIN TOPIC
# ============================================================

dot.node("A",
         "SYSTEM CAPABILITIES\nFOR\nVISION-BASED APPLICATIONS",
         shape="box",
         style="filled",
         fillcolor="lightblue",
         fontsize="22")

# ============================================================
# SYSTEM CAPABILITIES
# ============================================================

dot.node("B",
         "Processing Power\n(CPU / GPU)",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("C",
         "Memory Capacity",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("D",
         "Camera & Sensor Quality",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("E",
         "Storage & Data Handling",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("F",
         "Network & Communication",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

# ============================================================
# EFFECTS
# ============================================================

dot.node("G",
         "Real-Time Processing",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("H",
         "High Image Quality",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("I",
         "Fast Data Access",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("J",
         "Low Latency",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("K",
         "Reliable Performance",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

# ============================================================
# VISION PROCESSING
# ============================================================

dot.node("L",
         "Image Acquisition",
         shape="box",
         style="filled",
         fillcolor="khaki")

dot.node("M",
         "Image Preprocessing",
         shape="box")

dot.node("N",
         "Feature Extraction",
         shape="box")

dot.node("O",
         "Object Detection",
         shape="box")

dot.node("P",
         "Recognition & Decision Making",
         shape="box")

# ============================================================
# APPLICATIONS
# ============================================================

dot.node("Q",
         "Medical Imaging",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("R",
         "Autonomous Vehicles",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("S",
         "Face Recognition",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("T",
         "Industrial Inspection",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("U",
         "Surveillance Systems",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

# ============================================================
# PERFORMANCE
# ============================================================

dot.node("V",
         "Application Accuracy",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

dot.node("W",
         "System Efficiency",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

dot.node("X",
         "User Reliability",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

# ============================================================
# LITERATURE
# ============================================================

dot.node("Y",
         "Literature Perspectives\n\n"
         "• Gonzalez & Woods\nDigital Image Processing\n\n"
         "• Richard Szeliski\nComputer Vision\n\n"
         "• Forsyth & Ponce\nComputer Vision\n\n"
         "• Marr (Vision Theory)",
         shape="note",
         style="filled",
         fillcolor="lightyellow")

# ============================================================
# CONNECTIONS
# ============================================================

# Main
dot.edge("A","B")
dot.edge("A","C")
dot.edge("A","D")
dot.edge("A","E")
dot.edge("A","F")

# Capabilities -> Effects
dot.edge("B","G",label="enables")
dot.edge("C","K",label="supports")
dot.edge("D","H",label="improves")
dot.edge("E","I",label="provides")
dot.edge("F","J",label="reduces")

# Effects -> Processing
dot.edge("H","L")
dot.edge("G","M")
dot.edge("M","N")
dot.edge("N","O")
dot.edge("O","P")

dot.edge("I","P")
dot.edge("J","P")
dot.edge("K","P")

# Processing -> Performance
dot.edge("P","V",label="improves")
dot.edge("P","W",label="increases")
dot.edge("P","X",label="enhances")

# Performance -> Applications
dot.edge("V","Q")
dot.edge("V","R")
dot.edge("V","S")
dot.edge("W","T")
dot.edge("X","U")

# Literature
dot.edge("Y","A",label="supported by")

# ============================================================
# RENDER & DISPLAY
# ============================================================

filename = dot.render("System_Capabilities_Concept_Map")

display(Image(filename))

print("Concept Map generated successfully!")