# -*- coding: utf-8 -*-
"""cv-co1-at2-q04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5oQFmOrPBlOdfXrGRCsitTqn1x8zxAL
"""

# ============================================================
# CONCEPT MAP: IMAGE ACQUISITION CONDITIONS
# Google Colab Code
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

from graphviz import Digraph
from IPython.display import Image, display

# Create graph
dot = Digraph("ImageAcquisitionConditions", format="png")

# Graph settings
dot.attr(rankdir="TB")
dot.attr(size="15,15")
dot.attr(dpi="300")
dot.attr(nodesep="0.5")
dot.attr(ranksep="0.8")

# ============================================================
# MAIN NODE
# ============================================================

dot.node("A",
         "IMAGE ACQUISITION\nCONDITIONS",
         shape="box",
         style="filled",
         fillcolor="lightblue",
         fontsize="22")

# ============================================================
# IMAGE ACQUISITION FACTORS
# ============================================================

dot.node("B",
         "Lighting Conditions",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("C",
         "Camera Quality",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("D",
         "Sensor Characteristics",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("E",
         "Distance & Viewing Angle",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("F",
         "Motion",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

# ============================================================
# EFFECTS ON IMAGE
# ============================================================

dot.node("G",
         "Noise",
         shape="ellipse",
         style="filled",
         fillcolor="lightcoral")

dot.node("H",
         "Blur",
         shape="ellipse",
         style="filled",
         fillcolor="lightcoral")

dot.node("I",
         "Low Contrast",
         shape="ellipse",
         style="filled",
         fillcolor="lightcoral")

dot.node("J",
         "High Resolution",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("K",
         "Good Exposure",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

# ============================================================
# IMAGE PROCESSING
# ============================================================

dot.node("L",
         "Image Enhancement",
         shape="box",
         style="filled",
         fillcolor="khaki")

dot.node("M",
         "Noise Reduction",
         shape="box")

dot.node("N",
         "Contrast Enhancement",
         shape="box")

dot.node("O",
         "Image Restoration",
         shape="box")

dot.node("P",
         "Segmentation",
         shape="box")

dot.node("Q",
         "Feature Extraction",
         shape="box")

# ============================================================
# APPLICATION PERFORMANCE
# ============================================================

dot.node("R",
         "Improved Image Quality",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("S",
         "Better Detection Accuracy",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

dot.node("T",
         "Reliable Recognition",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

dot.node("U",
         "Higher System Performance",
         shape="box",
         style="filled",
         fillcolor="lightcyan")

# ============================================================
# APPLICATIONS
# ============================================================

dot.node("V", "Medical Imaging", shape="box")
dot.node("W", "Autonomous Vehicles", shape="box")
dot.node("X", "Face Recognition", shape="box")
dot.node("Y", "Remote Sensing", shape="box")

# ============================================================
# LITERATURE SUPPORT
# ============================================================

dot.node("Z",
         "Literature Support\n\n"
         "• Gonzalez & Woods\n"
         "Digital Image Processing\n\n"
         "• Richard Szeliski\n"
         "Computer Vision\n\n"
         "• Forsyth & Ponce\n"
         "Computer Vision",
         shape="note",
         style="filled",
         fillcolor="lightyellow")

# ============================================================
# RELATIONSHIPS
# ============================================================

# Main
dot.edge("A", "B")
dot.edge("A", "C")
dot.edge("A", "D")
dot.edge("A", "E")
dot.edge("A", "F")

# Acquisition → Effects
dot.edge("B", "I", label="poor lighting")
dot.edge("B", "K", label="good lighting")

dot.edge("C", "J", label="higher quality")
dot.edge("C", "G", label="low quality")

dot.edge("D", "G", label="sensor noise")

dot.edge("E", "H", label="incorrect angle")

dot.edge("F", "H", label="camera motion")

# Effects → Processing
dot.edge("G", "M")
dot.edge("H", "O")
dot.edge("I", "N")

dot.edge("J", "L")
dot.edge("K", "L")

dot.edge("L", "P")
dot.edge("P", "Q")

dot.edge("M", "R")
dot.edge("N", "R")
dot.edge("O", "R")

# Image Quality → Performance
dot.edge("R", "S")
dot.edge("S", "T")
dot.edge("T", "U")

# Applications
dot.edge("U", "V")
dot.edge("U", "W")
dot.edge("U", "X")
dot.edge("U", "Y")

# Literature
dot.edge("Z", "A", label="supported by")

# ============================================================
# SAVE & DISPLAY
# ============================================================

filename = dot.render("Image_Acquisition_Conditions_Concept_Map")

display(Image(filename))

print("Concept Map generated successfully!")