# -*- coding: utf-8 -*-
"""cv-co1-at1-q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15h5hFe-mD5DOaZRoRk_RJnEwNtTPtQbc
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
image = cv2.imread('Sample.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# -----------------------------
# Original Image
# -----------------------------

# Create aliasing by undersampling
small = cv2.resize(image, (image.shape[1]//6, image.shape[0]//6),
                   interpolation=cv2.INTER_NEAREST)

aliased = cv2.resize(small, (image.shape[1], image.shape[0]),
                     interpolation=cv2.INTER_NEAREST)

# -----------------------------
# Anti-aliasing
# -----------------------------

blurred = cv2.GaussianBlur(image, (5,5), 1.5)

small2 = cv2.resize(blurred, (image.shape[1]//6, image.shape[0]//6),
                    interpolation=cv2.INTER_AREA)

corrected = cv2.resize(small2, (image.shape[1], image.shape[0]),
                       interpolation=cv2.INTER_LINEAR)

# -----------------------------
# Quantization Example
# -----------------------------

levels = 16

quantized = np.floor(image/(256/levels))*(256/levels)
quantized = quantized.astype(np.uint8)

# -----------------------------
# Display Results
# -----------------------------

titles = [
    "Original",
    "Aliased Image",
    "Corrected Image",
    "Quantized Image"
]

images = [
    image,
    aliased,
    corrected,
    quantized
]

plt.figure(figsize=(18,8))

for i in range(len(images)):
    plt.subplot(1,4,i+1)
    plt.imshow(images[i])
    plt.title(titles[i])
    plt.axis("off")

plt.show()