# -*- coding: utf-8 -*-
"""cv-co1-at1-q05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHNDeQQsWRbFDuBQ32JjtrDg9lRWGNHL
"""

import cv2
import matplotlib.pyplot as plt

# Read image
image = cv2.imread("survelliance.jpg")

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Load pre-trained face detector
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

# Detect faces
faces = face_cascade.detectMultiScale(gray,
                                      scaleFactor=1.1,
                                      minNeighbors=5,
                                      minSize=(30,30))

# Draw rectangles
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0,255,0), 2)

# Convert to RGB for display
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Show result
plt.figure(figsize=(8,6))
plt.imshow(image)
plt.title(f"Detected Faces: {len(faces)}")
plt.axis("off")
plt.show()