# -*- coding: utf-8 -*-
"""cv-co1-at1-q06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDgGIGtWUhBqR0r4y3jnhliTz8eExwOX
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
image = cv2.imread("road.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# -------------------------------
# Step 1: Simulate Poor Image Formation
# -------------------------------

# Reduce brightness (night scene)
dark = (image * 0.4).astype(np.uint8)

# Add Gaussian blur (camera motion/fog)
blurred = cv2.GaussianBlur(dark, (7,7), 2)

# Add sensor noise
noise = np.random.normal(0, 15, blurred.shape).astype(np.int16)
noisy = blurred.astype(np.int16) + noise
noisy = np.clip(noisy, 0, 255).astype(np.uint8)

# -------------------------------
# Step 2: Image Enhancement
# -------------------------------

# Increase contrast using CLAHE
lab = cv2.cvtColor(noisy, cv2.COLOR_RGB2LAB)
l, a, b = cv2.split(lab)

clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
l = clahe.apply(l)

enhanced = cv2.merge((l,a,b))
enhanced = cv2.cvtColor(enhanced, cv2.COLOR_LAB2RGB)

# -------------------------------
# Display Results
# -------------------------------

titles = [
    "Original Image",
    "Poor Image Formation",
    "Enhanced Image"
]

images = [
    image,
    noisy,
    enhanced
]

plt.figure(figsize=(15,5))

for i in range(3):
    plt.subplot(1,3,i+1)
    plt.imshow(images[i])
    plt.title(titles[i])
    plt.axis("off")

plt.show()