# -*- coding: utf-8 -*-
"""cv-co1-at2-q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oBDhpzmcmuopClD8o67uZ957c7Sxpao
"""

# ============================================================
# CONCEPT MAP: FACTORS AFFECTING SPATIAL RESOLUTION
# Google Colab Code
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

from graphviz import Digraph
from IPython.display import Image, display

# ------------------------------------------------------------
# Create Concept Map
# ------------------------------------------------------------
dot = Digraph("SpatialResolution", format="png")

# Layout settings
dot.attr(rankdir="TB")
dot.attr(size="16,16")
dot.attr(dpi="300")
dot.attr(nodesep="0.5")
dot.attr(ranksep="0.8")
dot.attr(splines="ortho")

# ============================================================
# MAIN NODE
# ============================================================

dot.node(
    "A",
    "FACTORS AFFECTING\nSPATIAL RESOLUTION",
    shape="box",
    style="filled",
    fillcolor="lightblue",
    fontsize="22"
)

# ============================================================
# PRIMARY FACTORS
# ============================================================

dot.node("B",
         "Sampling Rate",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("C",
         "Pixel Density\n(Pixels per Inch)",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("D",
         "Sensor Resolution",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

dot.node("E",
         "Lens Quality",
         shape="box",
         style="filled",
         fillcolor="lightgreen")

# ============================================================
# EFFECTS
# ============================================================

dot.node("F",
         "More Pixels Captured",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("G",
         "Higher Detail",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("H",
         "Sharper Image",
         shape="ellipse",
         style="filled",
         fillcolor="palegreen")

dot.node("I",
         "Aliasing",
         shape="ellipse",
         style="filled",
         fillcolor="lightcoral")

dot.node("J",
         "Pixelation",
         shape="ellipse",
         style="filled",
         fillcolor="lightcoral")

# ============================================================
# IMAGE QUALITY
# ============================================================

dot.node("K",
         "Improved Image Quality",
         shape="box",
         style="filled",
         fillcolor="lightskyblue")

dot.node("L",
         "Reduced Image Quality",
         shape="box",
         style="filled",
         fillcolor="salmon")

# ============================================================
# APPLICATION REQUIREMENTS
# ============================================================

dot.node("M",
         "Application Requirements",
         shape="box",
         style="filled",
         fillcolor="khaki")

dot.node("N","Medical Imaging",shape="box")
dot.node("O","Satellite Imaging",shape="box")
dot.node("P","Face Recognition",shape="box")
dot.node("Q","Autonomous Vehicles",shape="box")
dot.node("R","Industrial Inspection",shape="box")

# ============================================================
# LITERATURE
# ============================================================

dot.node(
    "S",
    "Literature Support\n\n"
    "• Gonzalez & Woods\nDigital Image Processing\n\n"
    "• Richard Szeliski\nComputer Vision\n\n"
    "• Forsyth & Ponce\nComputer Vision\n\n"
    "• Anil K. Jain\nFundamentals of Digital Image Processing",
    shape="note",
    style="filled",
    fillcolor="lightyellow"
)

# ============================================================
# CONNECTIONS
# ============================================================

# Main branches
dot.edge("A","B")
dot.edge("A","C")
dot.edge("A","D")
dot.edge("A","E")

# Sampling
dot.edge("B","F",label="higher rate")
dot.edge("F","G",label="captures")
dot.edge("G","H",label="produces")
dot.edge("H","K")

dot.edge("B","I",label="low rate causes")
dot.edge("I","L")

# Pixel Density
dot.edge("C","G",label="increases")
dot.edge("C","J",label="low density causes")
dot.edge("J","L")

# Sensor & Lens
dot.edge("D","K",label="improves")
dot.edge("E","K",label="improves")

# Image Quality
dot.edge("K","M",label="supports")
dot.edge("L","M",label="limits")

# Applications
dot.edge("M","N")
dot.edge("M","O")
dot.edge("M","P")
dot.edge("M","Q")
dot.edge("M","R")

# Literature
dot.edge("S","A",label="supported by")

# ============================================================
# SAVE & DISPLAY
# ============================================================

filename = dot.render("Spatial_Resolution_Concept_Map")

display(Image(filename))

print("Concept Map generated successfully!")