# -*- coding: utf-8 -*-
"""Lab Exp 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvRS1KM0wVNu5mE4wQnIENJugO31VEgk
"""

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('Sample.jpg')
blur = cv2.GaussianBlur(image, (31,31), 0)
cv2.imwrite('blurred_image.jpg', blur)
cv2_imshow(blur)
cv2.waitKey(0)
cv2.destroyAllWindows()