# -*- coding: utf-8 -*-
"""cv-co1-at1-q04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4mhLEWcaS8nPpEfnk_TRVa92yGxbIcT
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read grayscale medical image
image = cv2.imread('medical.jpg', cv2.IMREAD_GRAYSCALE)

# -----------------------------
# Pixel Resolution Reduction
# -----------------------------
small = cv2.resize(image, (image.shape[1]//4, image.shape[0]//4),
                   interpolation=cv2.INTER_AREA)

low_pixel = cv2.resize(small,
                       (image.shape[1], image.shape[0]),
                       interpolation=cv2.INTER_NEAREST)

# -----------------------------
# Intensity Resolution Reduction
# -----------------------------
levels = 16        # 4-bit intensity (16 gray levels)

low_intensity = np.floor(image/(256/levels))*(256/levels)
low_intensity = low_intensity.astype(np.uint8)

# -----------------------------
# Display
# -----------------------------
titles = [
    "Original Image",
    "Low Pixel Resolution",
    "Low Intensity Resolution"
]

images = [
    image,
    low_pixel,
    low_intensity
]

plt.figure(figsize=(15,5))

for i in range(3):
    plt.subplot(1,3,i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis("off")

plt.show()