# -*- coding: utf-8 -*-
"""cv-co1-at2-q03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8-1RQkxLOSOSLrV6U4GsDNpnyLAdSI9
"""

# ============================================================
# CONCEPT MAP: IMAGE RESOLUTION & INTENSITY LEVELS
# Google Colab Code
# ============================================================

# Install Graphviz
!apt-get -qq install graphviz
!pip -q install graphviz

from graphviz import Digraph
from IPython.display import Image, display

# Create the concept map
dot = Digraph('ConceptMap', format='png')

# Layout Settings
dot.attr(rankdir='TB')          # Top to Bottom
dot.attr(size='14,14')
dot.attr(dpi='300')
dot.attr(nodesep='0.5')
dot.attr(ranksep='0.8')

# ----------------------------
# Main Topic
# ----------------------------
dot.node('A',
         'IMAGE RESOLUTION\nAND\nINTENSITY LEVELS',
         shape='box',
         style='filled',
         fillcolor='lightblue',
         fontsize='22')

# ----------------------------
# Resolution Section
# ----------------------------
dot.node('B',
         'Image Resolution\n(Number of Pixels)',
         shape='box',
         style='filled',
         fillcolor='lightgreen')

dot.node('C',
         'High Resolution',
         shape='ellipse',
         style='filled',
         fillcolor='palegreen')

dot.node('D',
         'Low Resolution',
         shape='ellipse',
         style='filled',
         fillcolor='lightcoral')

dot.node('E',
         'More Pixels',
         shape='box')

dot.node('F',
         'More Image Details',
         shape='box')

dot.node('G',
         'Sharper Edges',
         shape='box')

dot.node('H',
         'Pixelation',
         shape='box')

dot.node('I',
         'Loss of Detail',
         shape='box')

# ----------------------------
# Intensity Section
# ----------------------------
dot.node('J',
         'Intensity Levels\n(Bit Depth)',
         shape='box',
         style='filled',
         fillcolor='khaki')

dot.node('K',
         'Higher Bit Depth\n(8-bit / 16-bit)',
         shape='ellipse',
         style='filled',
         fillcolor='palegreen')

dot.node('L',
         'Lower Bit Depth',
         shape='ellipse',
         style='filled',
         fillcolor='lightcoral')

dot.node('M',
         'Smooth Brightness\nTransitions',
         shape='box')

dot.node('N',
         'High Dynamic Range',
         shape='box')

dot.node('O',
         'Banding Effect',
         shape='box')

dot.node('P',
         'Reduced Contrast',
         shape='box')

# ----------------------------
# Image Quality
# ----------------------------
dot.node('Q',
         'High Image Quality',
         shape='box',
         style='filled',
         fillcolor='lightskyblue')

dot.node('R',
         'Low Image Quality',
         shape='box',
         style='filled',
         fillcolor='salmon')

# ----------------------------
# Usability
# ----------------------------
dot.node('S',
         'Improved Usability',
         shape='box',
         style='filled',
         fillcolor='lightcyan')

dot.node('T',
         'Reduced Usability',
         shape='box',
         style='filled',
         fillcolor='mistyrose')

dot.node('U',
         'Medical Imaging',
         shape='box')

dot.node('V',
         'Remote Sensing',
         shape='box')

dot.node('W',
         'Face Recognition',
         shape='box')

dot.node('X',
         'Autonomous Driving',
         shape='box')

# ----------------------------
# Literature Support
# ----------------------------
dot.node('Y',
         'Literature Support\n\n'
         '• Gonzalez & Woods\n'
         'Digital Image Processing\n\n'
         '• Szeliski\n'
         'Computer Vision\n\n'
         '• Forsyth & Ponce\n'
         'Computer Vision',
         shape='note',
         style='filled',
         fillcolor='lightyellow')

# ----------------------------
# Connections
# ----------------------------

# Main branches
dot.edge('A','B')
dot.edge('A','J')

# Resolution
dot.edge('B','C',label='Higher')
dot.edge('B','D',label='Lower')

dot.edge('C','E',label='increases')
dot.edge('E','F',label='results in')
dot.edge('F','G',label='improves')
dot.edge('G','Q')

dot.edge('D','H',label='causes')
dot.edge('H','I')
dot.edge('I','R')

# Intensity
dot.edge('J','K',label='Higher')
dot.edge('J','L',label='Lower')

dot.edge('K','M',label='provides')
dot.edge('K','N',label='improves')
dot.edge('M','Q')
dot.edge('N','Q')

dot.edge('L','O',label='causes')
dot.edge('O','P')
dot.edge('P','R')

# Image Quality
dot.edge('Q','S',label='leads to')
dot.edge('R','T',label='leads to')

# Applications
dot.edge('S','U')
dot.edge('S','V')
dot.edge('S','W')
dot.edge('S','X')

# Literature
dot.edge('Y','A',label='supported by')

# Save and display
filename = dot.render('Image_Resolution_Intensity_Concept_Map')

display(Image(filename))

print("Concept Map generated successfully!")