# -*- coding: utf-8 -*-
"""Lab exp_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EecCj0z0R7Om7OOSfMqR4g_LW7AGfX_X
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
img = cv2.imread("Sample.jpg")
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
eroded_image = cv2.erode(gray_image, kernel, iterations=1)
cv2.imwrite("eroded_image.jpg",eroded_image)
cv2_imshow(eroded_image)